# permissions for end users to edit motds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: twisted-dispatch
    app.kubernetes.io/managed-by: kustomize
  name: motd-editor-role
rules:
- apiGroups:
  - dispatch.twistedsolutions.se
  resources:
  - motds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dispatch.twistedsolutions.se
  resources:
  - motds/status
  verbs:
  - get
