apiVersion: dispatch.twistedsolutions.se/v1alpha1
kind: Motd
metadata:
  labels:
    app.kubernetes.io/name: twisted-dispatch
    app.kubernetes.io/managed-by: kustomize
  name: motd-sample
  namespace: default
spec:
  components:
  - type: text
    text: "Welcome to the Twisted Dispatch demo! 🚀"
  # - type: divider
  # - type: text
  #   text: "🔆 Weather"
  #   style:
  #   - bold
  #   - underline
  # - type: weather
  #   city: "Stockholm"
  #   weatherAPIKeySecretRef:
  #     name: weather-api-key
  #     key: api-key
  # - type: weather
  #   city: "London"
  #   weatherAPIKeySecretRef:
  #     name: weather-api-key
  #     key: api-key
  - type: divider
  - type: text
    text: "🤖 Cluster Status"
    style:
    - bold
    - underline
  - type: nodeStatus
  - type: clusterOperatorStatus
